project: tblochii_wgs

samples: config/samples.tsv
phenotypes: config/phenotypes.tsv
chromosomes: config/chromosomes.txt

reference:
  fasta: resources/Tov.fa
  gff3: resources/Tov_rename.gff3
  functional_annotation: ""

analysis:
  ploidy: 2
  censor_time_h: 24
  stage4_call_rate: 0.80
  downstream_status_exclude: [2]
  binary_tail_fraction: 0.30
  binary_boundary_ties: exclude_all
  candidate_p: 1.0e-5
  clump_p1: 1.0e-5
  clump_p2: 1.0e-5
  clump_r2: 0.2
  clump_kb: 500

hard_filter:
  QD: 2.0
  FS: 60.0
  SOR: 3.0
  MQ: 40.0
  MQRankSum: -12.5
  ReadPosRankSum: -8.0

beagle:
  jar: resources/beagle.5.5.jar
  java_mem_gb: 24
  window: 2
  overlap: 0.2
  threads: 4
  apply_dr2_filter: false

plink_qc:
  mind: 0.1
  geno: 0.1
  maf: 0.05
  ld_window: 50
  ld_step: 10
  ld_r2: 0.2

population_structure:
  pca_components: 10
  admixture_k_min: 2
  admixture_k_max: 60
  admixture_cv_folds: 10

resources:
  fastqc_threads: 2
  alignment_threads: 4
  haplotypecaller_threads: 4
  genomicsdb_threads: 4
  plink_threads: 8
  pca_threads: 8
  admixture_threads: 4

run:
  fastq_qc: true
  population_structure: true
  continuous_gwas: true
  binary_gwas: true
  cox_gwas: true
  candidate_annotation: true
